In [2]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
print(torch.__version__)

2.13.0


## Introduction to Tensors

### Creating tensors


In [6]:
# scalor
scalor = torch.tensor(7)
scalor

tensor(7)

In [ ]:
scalor.ndim

0

In [8]:
# get tensor back as python int 
scalor.item()

7

In [9]:
# Vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [3]:
# MATRIX

matrix = torch.tensor([[1,2,10],[20,23,12]])
matrix

tensor([[ 1,  2, 10],
        [20, 23, 12]])

In [4]:
matrix.shape
matrix.ndim

2

In [5]:
matrix.shape

torch.Size([2, 3])

In [9]:
matrixxx = torch.tensor([[[1,2],[2,3],[3,4]]])
matrixxx.shape

torch.Size([1, 3, 2])

In [8]:
matrixxx.ndim

3

In [17]:
exceptional = torch.tensor([[[[[12,21],[23,32]]],[[[12,21],[23,32]]],[[[12,21],[23,32]]]]])
exceptional

tensor([[[[[12, 21],
           [23, 32]]],


         [[[12, 21],
           [23, 32]]],


         [[[12, 21],
           [23, 32]]]]])

In [18]:
exceptional.ndim


5

In [19]:
exceptional.shape

torch.Size([1, 3, 1, 2, 2])

In [20]:
# Random tensors 

random_tensers = torch.rand(2,3)
random_tensers

tensor([[0.2928, 0.0082, 0.3508],
        [0.7664, 0.4322, 0.7597]])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height, width,  color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
random_image_size_tensor

tensor([[[0.2459, 0.0800, 0.2550],
         [0.0800, 0.0783, 0.5689],
         [0.7629, 0.3263, 0.2001],
         ...,
         [0.9660, 0.8093, 0.2319],
         [0.8347, 0.0433, 0.5286],
         [0.0883, 0.2734, 0.7418]],

        [[0.6864, 0.0434, 0.4072],
         [0.9974, 0.5593, 0.4350],
         [0.5587, 0.4188, 0.8586],
         ...,
         [0.3394, 0.8489, 0.0878],
         [0.7037, 0.8704, 0.3170],
         [0.3188, 0.1846, 0.4844]],

        [[0.0844, 0.4071, 0.2362],
         [0.2698, 0.0134, 0.6755],
         [0.2330, 0.1148, 0.2905],
         ...,
         [0.0890, 0.9809, 0.4989],
         [0.8584, 0.2199, 0.1172],
         [0.2179, 0.4178, 0.7914]],

        ...,

        [[0.1151, 0.3534, 0.1703],
         [0.7664, 0.9605, 0.7748],
         [0.1519, 0.0866, 0.2869],
         ...,
         [0.3731, 0.4019, 0.4468],
         [0.5680, 0.5561, 0.2984],
         [0.9048, 0.3198, 0.0224]],

        [[0.1786, 0.7191, 0.9472],
         [0.1572, 0.3768, 0.9135],
         [0.