In [2]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
print(torch.__version__)

2.13.0


## Introduction to Tensors

### Creating tensors


In [6]:
# scalor
scalor = torch.tensor(7)
scalor

tensor(7)

In [ ]:
scalor.ndim

0

In [8]:
# get tensor back as python int 
scalor.item()

7

In [9]:
# Vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [3]:
# MATRIX

matrix = torch.tensor([[1,2,10],[20,23,12]])
matrix

tensor([[ 1,  2, 10],
        [20, 23, 12]])

In [4]:
matrix.shape
matrix.ndim

2

In [5]:
matrix.shape

torch.Size([2, 3])

In [9]:
matrixxx = torch.tensor([[[1,2],[2,3],[3,4]]])
matrixxx.shape

torch.Size([1, 3, 2])

In [8]:
matrixxx.ndim

3

In [17]:
exceptional = torch.tensor([[[[[12,21],[23,32]]],[[[12,21],[23,32]]],[[[12,21],[23,32]]]]])
exceptional

tensor([[[[[12, 21],
           [23, 32]]],


         [[[12, 21],
           [23, 32]]],


         [[[12, 21],
           [23, 32]]]]])

In [18]:
exceptional.ndim


5

In [19]:
exceptional.shape

torch.Size([1, 3, 1, 2, 2])